# background_colour = [0.0, 0.0, 0.0]
background_colour = [0.04, 0.06, 0.16]
# background_colour = [0.5, 0.6, 0.8]

[[objects]]
type = "Sphere"
centre = [0.0, 0.0, -100.5]
radius = 100.0

[objects.material]
emission = 0.0
metallic = 0.0
specular = 0.0
transparency = 0.0
roughness = 0.0
ior = 1.5

[objects.material.texture]
type = "CheckerTexture"
scale = 10.0

[objects.material.texture.even]
type = "SolidColour"
colour = [0.2, 0.3, 0.1]

[objects.material.texture.odd]
type = "SolidColour"
colour = [0.9, 0.9, 0.9]

[[objects]]
type = "Sphere"
centre = [0.0, 0.0, 0.0]
radius = 0.5

[objects.material]
emission = 0.0
metallic = 0.0
specular = 1.0
transparency = 0.0
roughness = 0.0
ior = 1.5

[objects.material.texture]
type = "SolidColour"
colour = [0.1, 0.2, 0.5]

[[objects]]
type = "Sphere"
centre = [-1.0, 0.0, 0.0]
radius = 0.5

[objects.material]
emission = 0.0
metallic = 0.0
specular = 1.0
transparency = 1.0
roughness = 0.05
ior = 1.5

[objects.material.texture]
type = "SolidColour"
colour = [0.8, 0.35, 0.35]

[[objects]]
type = "Sphere"
centre = [1.0, 0.0, 0.0]
radius = 0.5

[objects.material]
emission = 0.0
metallic = 1.0
specular = 0.0
transparency = 0.0
roughness = 0.3
ior = 1.5

[objects.material.texture]
type = "SolidColour"
colour = [0.8, 0.6, 0.2]

[[objects]]
type = "Sphere"
centre = [0.0, 1.0, 2.0]
radius = 1.0

[objects.material]
emission = 1.0
metallic = 0.0
specular = 0.0
transparency = 0.0
roughness = 0.0
ior = 1.5

[objects.material.texture]
type = "SolidColour"
colour = [2.0, 1.6, 1.5]

[[objects]]
type = "Triangle"
a = [0.5, 0.0, 0.0]
b = [0.5, -1.0, 0.0]
c = [0.5, 0.0, 1.0]

[objects.material]
emission = 0.0
metallic = 0.0
specular = 1.0
transparency = 1.0
roughness = 0.00
ior = 1.5

[objects.material.texture]
type = "SolidColour"
colour = [0.8, 0.8, 0.8]

[camera]
pos = [-1.0, -2.0, 1.5]
look_at = [0.0, 0.0, 0.0]
aspect_ratio = 1.0
fov = 50.0
aperture = 0.1
